services:
  backend:
    build:
      context: ./Backend
    container_name: rag_ccb_backend
    ports:
      - "9000:9000"
    volumes:
      - ./Backend:/app
      - ./Data:/app/Data
    depends_on:
      - chromodb
      # - ollama
  frontend:
    build:
      context: ./Frontend
    container_name: rag_ccb_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
  chromodb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: rag_ccb_chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_models:/root/.ollama
  #   restart: always

volumes:
  chromadb_data:
  # ollama_models: